In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from pandas import DataFrame 
import nltk

from sklearn.neighbors import NearestNeighbors
from sklearn.linear_model import LogisticRegression
from sklearn import neighbors
from scipy.spatial.distance import cosine
from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score
from sklearn.feature_selection import SelectKBest
from sklearn.feature_extraction.text import CountVectorizer, TfidfTransformer

import re
import string
from sklearn.metrics import mean_squared_error

In [2]:
df = pd.read_json("Office_Products_5.json", lines=True)
print(df.columns)
print(df.shape)

Index(['asin', 'helpful', 'overall', 'reviewText', 'reviewTime', 'reviewerID',
       'reviewerName', 'summary', 'unixReviewTime'],
      dtype='object')
(53258, 9)


In [3]:
df = df.sort_values(by='asin')
df = df.reset_index(drop=True)
count = df.groupby("asin", as_index=False).mean()
count_users = df.groupby("reviewerID", as_index=False).count()

df_clean = df[['asin', 'reviewerID', 'overall']]
print(df_clean)

             asin      reviewerID  overall
0      B00000JBLH  A32T2H8150OJLU        5
1      B00000JBLH  A3MAFS04ZABRGO        5
2      B00000JBLH  A1F1A0QQP2XVH5        2
3      B00000JBLH   A49R5DBXXQDE5        5
4      B00000JBLH  A2XRMQA6PJ5ZJ8        5
5      B00000JBLH  A2JFOHC9W629IE        5
6      B00000JBLH  A38NELQT98S4H8        5
7      B00000JBLH   AA8M6331NI1EN        5
8      B00000JBLU  A1LYT85S93HUNY        5
9      B00000JBLU   A4XCTN5YLC89U        5
10     B00000JBLU  A2A1XYSB692L6J        4
11     B00000JBLU   AGBFIQMV9L61Y        5
12     B00000JBLU  A2R6RA8FRBS608        5
13     B00000JBLU  A30U2QQN2FFHE9        5
14     B00000JBLU  A1RTVWTWZSIC94        5
15     B00000JBLU  A25C2M3QF9G7OQ        5
16     B00000JBLU  A2W0XCWOK3MW6F        5
17     B00000JBNX   A6KL17KKN0A5L        5
18     B00000JBNX  A3LZA698SQPCXE        5
19     B00000JBNX   AO9X6644SGODF        5
20     B00000JBNX   AOUM75FA941HX        2
21     B00000JBNX  A36OT34BWUV59E        5
22     B000

In [4]:
n_users = df_clean.reviewerID.unique().shape[0]
n_items = df_clean.asin.unique().shape[0]
print ('Number of movies = ' + str(n_items)+' | Number of users = ' + str(n_users))

Number of movies = 2420 | Number of users = 4905


In [5]:
count_users.loc[count_users['reviewerID'] == 'AZ9WQM7SLUX7E']

reviewerID  asin  helpful  overall  reviewText  reviewTime  \
4877  AZ9WQM7SLUX7E    21       21       21          21          21   

      reviewerName  summary  unixReviewTime  
4877            20       21              21

In [6]:
items_df = count[['asin']]
items_df
users_df = count_users[['reviewerID']]
users_df
users_list = users_df.values
users_list

array([['A00473363TJ8YSZ3YAGG9'],
       ['A04324702R5O7JRSQNVAH'],
       ['A0678500JUN3N7KUG4PS'],
       ...,
       ['AZYJE40XW6MFG'],
       ['AZZ5ASC403N74'],
       ['AZZD30PYJVGI7']], dtype=object)

In [7]:
from sklearn.model_selection import train_test_split
trainSet, testSet = train_test_split(df_clean, test_size=0.2,stratify=df_clean['reviewerID'])

print(len(testSet))
print(len(trainSet))

print(testSet.shape)
print(trainSet.shape)


10652
42606
(10652, 3)
(42606, 3)


In [8]:
mean_items = trainSet.groupby(['asin']).mean()

mean_users = trainSet.groupby(['reviewerID']).mean()

mean_overall = trainSet["overall"].mean()

print(mean_items,mean_users,mean_overall)

             overall
asin                
B00000JBLH  4.571429
B00000JBLU  4.857143
B00000JBNX  4.333333
B00000JBO8  4.000000
B00000JFNV  4.757576
B00000JZKB  4.000000
B00000K3T0  5.000000
B00001MXVQ  3.333333
B00002NDS2  4.785714
B00002QUKW  5.000000
B000031WDB  3.846154
B000034DLQ  4.142857
B0000365QL  4.666667
B00003CYNU  5.000000
B00004SDB1  4.400000
B00004SUJT  5.000000
B00004TS2I  5.000000
B00004TS2L  4.857143
B00004U8RE  4.700000
B00004VVIX  4.300000
B00004YTPX  4.200000
B00004YV1W  4.142857
B00004Z47L  5.000000
B00004Z498  4.705882
B00004Z4A8  4.666667
B00004Z4BV  4.888889
B00004Z59A  4.190476
B00004Z5DW  4.142857
B00004Z5QI  4.285714
B00004Z5QO  4.719298
...              ...
B00J8NBVYE  4.444444
B00J8U9QCG  4.133333
B00J9E68B8  4.000000
B00JAKXFQW  4.590909
B00JBK74IQ  4.358974
B00JBVWDB8  4.800000
B00JCA4GQS  4.571429
B00JCA4GW2  4.666667
B00JHME7W4  4.000000
B00JIX4OTI  4.545455
B00JIX53PW  5.000000
B00JIXXHEG  4.200000
B00JJRMPPS  4.615385
B00JJS7JXK  3.566667
B00JKQV90A  3

In [9]:
trainSet

asin      reviewerID  overall
20944  B002FGUDBS   ATFBVUXDIRXT6        5
38024  B005IMAKYG  A3H7NPNDMGLOU4        5
13315  B0010JEJPC   AMW1OYXWOGZGJ        5
41923  B0085IQ28I  A15T9G38F589KM        2
44729  B009ZMWHIC  A32E5G5T902WRV        1
46841  B00BV1XGGM    ADLVFFE4VBT8        4
33841  B004INGE4G  A2UQIQUOAB47OT        5
31772  B00466DTE8  A1I477ADGMLVJM        3
14954  B0015G39OW  A2FZQF0MH29VYN        4
47608  B00CPXCVIO  A194K60CWZ371J        3
10495  B000JCTH2Q   AKN6V9Y0YH421        5
5099   B00008XPLC  A26IPZJ4OA05RU        5
16708  B001CRYXHG  A1KXJCXS6HFRQZ        5
25151  B002V3SSBW  A185QFJRTB5W93        5
32310  B004DMAZOC  A1BAJ6JXU8PSZH        5
49250  B00EANUUDK  A19UTUEBWKIZFT        5
29991  B003RL7RRS  A1VHERKT2KX0MO        3
19244  B001TANFHA  A1UBSC80601DN1        5
34811  B004OA74MY  A27BM0VZSVKXZD        4
39972  B0067Y5TI6  A2IPC51HL9UUYF        5
51175  B00G4TYP5W  A22I55P15NSAOX        5
42350  B008DF54N2  A3HG0DNFURFXR4        5
33323  B004HO58UW  A23E9OI4NA1W29        3
17449  B001F0RI1I  A10XW9CASORTU6        5
26526  B0036D5XH8  A1189NRXDCRHUH        5
25732  B0032OREFU  A3QEJ40NQEW36Q        3
11180  B000MVV6AA  A1EX5SK2PD0XLC        5
304    B00004Z498   A28ZDVY6NV75P        4
16549  B001CE3AUU  A2I98OOPNIJNYY        4
18929  B001PV36V8   ADY836HK6QSYR        4
...           ...             ...      ...
43049  B008PAIC4S  A3T3S48UAVTUE9        5
19806  B0026MBCXO  A3VSY7JOVU13GE        2
25444  B002XYO84U   AV3XTMK5I2AWI        5
4389   B00006JNJ8  A1ROCGU2YILTNX        5
17102  B001DPSUUI  A11T807LX2EF00        5
42196  B008CO4NCC   AUEY946M1L939        5
27461  B0039N7ELS   ATN4J5VS8Q0YM        5
34359  B004N4JIB6  A2P6QCZWW3H1X6        4
31384  B00445V2M2  A12E0Y0J6584RT        5
26724  B0036TGGVO  A3PGRIMNNL5WKE        5
18773  B001PMJXYG   AIIR8E34EDKCQ        5
34113  B004LY27PW  A28OB1QLXN5BM6        5
45502  B00AQ2BZZQ  A1ODOGXEYECQQ8        4
17889  B001IKKIVW  A100WO06OQR8BQ        5
43130  B008YD1V6C  A172LET5CHK02U        5
915    B0000538AC   ASW22V6LI995Z        5
4041   B00006IFKT  A1UG4J8DEG9NVW        5
39461  B005YGLA5Y   ATR2C537XOMQ0        5
43463  B0091UBCAW  A221AYJCX6Y5WB        5
11085  B000MK4RAM  A1YY6103EIE3H4        5
46024  B00AYUI490  A27FP0S5QH7GNE        5
24871  B002R5ARLI   AZKGCE3LNX7WB        4
35901  B004VJSG2A  A1C7Y31S5QXNTR        4
3990   B00006IFIM  A2JROMDHVIUSKB        5
35271  B004UMNN2G  A2QRXQPHDMFCQV        4
28804  B003I869CY  A2L4ZGN7GZJ95T        5
25834  B0033UU1J4  A1M92239OM8KPO        5
42995  B008OEHWYG   AZFHSPEZUPGD2        5
19529  B0025Z3J38   A8EBWQZIDKF78        4
41282  B007VGM090   AW6A72DBAELE1        3

[42606 rows x 3 columns]

In [10]:
# print(trainSet.groupby("asin", as_index=False).count())

In [11]:
train_data_matrix_na = trainSet.pivot(index='asin', columns='reviewerID', values='overall')
train_data_matrix = train_data_matrix_na
train_data_matrix

reviewerID  A00473363TJ8YSZ3YAGG9  A04324702R5O7JRSQNVAH  \
asin                                                       
B00000JBLH                    NaN                    NaN   
B00000JBLU                    NaN                    NaN   
B00000JBNX                    NaN                    NaN   
B00000JBO8                    NaN                    NaN   
B00000JFNV                    NaN                    NaN   
B00000JZKB                    NaN                    NaN   
B00000K3T0                    NaN                    NaN   
B00001MXVQ                    NaN                    NaN   
B00002NDS2                    NaN                    NaN   
B00002QUKW                    NaN                    NaN   
B000031WDB                    NaN                    NaN   
B000034DLQ                    NaN                    NaN   
B0000365QL                    NaN                    NaN   
B00003CYNU                    NaN                    NaN   
B00004SDB1                    NaN                    NaN   
B00004SUJT                    NaN                    NaN   
B00004TS2I                    NaN                    NaN   
B00004TS2L                    NaN                    NaN   
B00004U8RE                    NaN                    NaN   
B00004VVIX                    NaN                    NaN   
B00004YTPX                    NaN                    NaN   
B00004YV1W                    NaN                    NaN   
B00004Z47L                    NaN                    NaN   
B00004Z498                    NaN                    NaN   
B00004Z4A8                    NaN                    NaN   
B00004Z4BV                    NaN                    NaN   
B00004Z59A                    NaN                    NaN   
B00004Z5DW                    NaN                    NaN   
B00004Z5QI                    NaN                    NaN   
B00004Z5QO                    NaN                    NaN   
...                           ...                    ...   
B00J8NBVYE                    NaN                    NaN   
B00J8U9QCG                    NaN                    NaN   
B00J9E68B8                    NaN                    NaN   
B00JAKXFQW                    NaN                    NaN   
B00JBK74IQ                    NaN                    NaN   
B00JBVWDB8                    NaN                    NaN   
B00JCA4GQS                    NaN                    NaN   
B00JCA4GW2                    NaN                    NaN   
B00JHME7W4                    NaN                    NaN   
B00JIX4OTI                    NaN                    NaN   
B00JIX53PW                    NaN                    NaN   
B00JIXXHEG                    NaN                    NaN   
B00JJRMPPS                    NaN                    NaN   
B00JJS7JXK                    NaN                    NaN   
B00JKQV90A                    NaN                    NaN   
B00JKRE0JG                    NaN                    NaN   
B00JKRKFQI                    NaN                    NaN   
B00JKRKP22                    NaN                    NaN   
B00JQXRWQM                    NaN                    NaN   
B00JXLGELG                    NaN                    NaN   
B00JXLGESY                    NaN                    NaN   
B00JXLGETI                    NaN                    NaN   
B00JXLGETS                    NaN                    NaN   
B00JXLGEUC                    NaN                    NaN   
B00JXLGF06                    NaN                    NaN   
B00K5UZP2S                    NaN                    NaN   
B00KLLBEPI                    NaN                    NaN   
B00KOO594O                    NaN                    NaN   
B00KOO599O                    NaN                    NaN   
B00KYA0RC2                    NaN                    NaN   

reviewerID  A0678500JUN3N7KUG4PS  A100UD67AHFODS  A100WO06OQR8BQ  \
asin                                                               
B00000JBLH                   NaN             NaN             NaN   
B00000JBLU     

In [12]:
train_values = train_data_matrix.values
train_sum = train_data_matrix.sum(axis = 1)
train_count = train_data_matrix.count(axis =1).astype('float64')
train_normal = train_sum.div(train_count,axis=0)

train_data_matrix = train_data_matrix.sub(train_normal,axis=0).fillna(0)
train_data_matrix

reviewerID  A00473363TJ8YSZ3YAGG9  A04324702R5O7JRSQNVAH  \
asin                                                       
B00000JBLH                    0.0                    0.0   
B00000JBLU                    0.0                    0.0   
B00000JBNX                    0.0                    0.0   
B00000JBO8                    0.0                    0.0   
B00000JFNV                    0.0                    0.0   
B00000JZKB                    0.0                    0.0   
B00000K3T0                    0.0                    0.0   
B00001MXVQ                    0.0                    0.0   
B00002NDS2                    0.0                    0.0   
B00002QUKW                    0.0                    0.0   
B000031WDB                    0.0                    0.0   
B000034DLQ                    0.0                    0.0   
B0000365QL                    0.0                    0.0   
B00003CYNU                    0.0                    0.0   
B00004SDB1                    0.0                    0.0   
B00004SUJT                    0.0                    0.0   
B00004TS2I                    0.0                    0.0   
B00004TS2L                    0.0                    0.0   
B00004U8RE                    0.0                    0.0   
B00004VVIX                    0.0                    0.0   
B00004YTPX                    0.0                    0.0   
B00004YV1W                    0.0                    0.0   
B00004Z47L                    0.0                    0.0   
B00004Z498                    0.0                    0.0   
B00004Z4A8                    0.0                    0.0   
B00004Z4BV                    0.0                    0.0   
B00004Z59A                    0.0                    0.0   
B00004Z5DW                    0.0                    0.0   
B00004Z5QI                    0.0                    0.0   
B00004Z5QO                    0.0                    0.0   
...                           ...                    ...   
B00J8NBVYE                    0.0                    0.0   
B00J8U9QCG                    0.0                    0.0   
B00J9E68B8                    0.0                    0.0   
B00JAKXFQW                    0.0                    0.0   
B00JBK74IQ                    0.0                    0.0   
B00JBVWDB8                    0.0                    0.0   
B00JCA4GQS                    0.0                    0.0   
B00JCA4GW2                    0.0                    0.0   
B00JHME7W4                    0.0                    0.0   
B00JIX4OTI                    0.0                    0.0   
B00JIX53PW                    0.0                    0.0   
B00JIXXHEG                    0.0                    0.0   
B00JJRMPPS                    0.0                    0.0   
B00JJS7JXK                    0.0                    0.0   
B00JKQV90A                    0.0                    0.0   
B00JKRE0JG                    0.0                    0.0   
B00JKRKFQI                    0.0                    0.0   
B00JKRKP22                    0.0                    0.0   
B00JQXRWQM                    0.0                    0.0   
B00JXLGELG                    0.0                    0.0   
B00JXLGESY                    0.0                    0.0   
B00JXLGETI                    0.0                    0.0   
B00JXLGETS                    0.0                    0.0   
B00JXLGEUC                    0.0                    0.0   
B00JXLGF06                    0.0                    0.0   
B00K5UZP2S                    0.0                    0.0   
B00KLLBEPI                    0.0                    0.0   
B00KOO594O                    0.0                    0.0   
B00KOO599O                    0.0                    0.0   
B00KYA0RC2                    0.0                    0.0   

reviewerID  A0678500JUN3N7KUG4PS  A100UD67AHFODS  A100WO06OQR8BQ  \
asin                                                               
B00000JBLH                   0.0             0.0        0.000000   
B00000JBLU     

In [13]:
test_data_matrix_na = testSet.pivot(index='asin', columns='reviewerID', values='overall')
test_data_matrix = test_data_matrix_na.fillna(0)
test_data_matrix

reviewerID  A00473363TJ8YSZ3YAGG9  A04324702R5O7JRSQNVAH  \
asin                                                       
B00000JBLH                    0.0                    0.0   
B00000JBLU                    0.0                    0.0   
B00000JBNX                    0.0                    0.0   
B00000JBO8                    0.0                    0.0   
B00000JFNV                    0.0                    0.0   
B00000JZKB                    0.0                    0.0   
B00000K3T0                    0.0                    0.0   
B00001MXVQ                    0.0                    0.0   
B00002NDS2                    0.0                    0.0   
B00002QUKW                    0.0                    0.0   
B000031WDB                    0.0                    0.0   
B0000365QL                    0.0                    0.0   
B00004SUJT                    0.0                    0.0   
B00004TS2I                    0.0                    0.0   
B00004TS2L                    0.0                    0.0   
B00004U8RE                    0.0                    0.0   
B00004VVIX                    0.0                    0.0   
B00004YTPX                    0.0                    0.0   
B00004YV1W                    0.0                    0.0   
B00004Z498                    0.0                    0.0   
B00004Z4A8                    0.0                    0.0   
B00004Z4BV                    0.0                    0.0   
B00004Z59A                    0.0                    0.0   
B00004Z5DW                    0.0                    0.0   
B00004Z5QI                    0.0                    0.0   
B00004Z5QO                    0.0                    0.0   
B00004Z5QP                    0.0                    0.0   
B00004Z5RA                    0.0                    0.0   
B00004Z5SB                    0.0                    0.0   
B00004Z5SM                    0.0                    0.0   
...                           ...                    ...   
B00IQBT3RG                    0.0                    0.0   
B00IQBT3VW                    0.0                    0.0   
B00IX1LZAC                    0.0                    0.0   
B00IZL23MY                    0.0                    0.0   
B00J61901Y                    0.0                    0.0   
B00J8U9QCG                    0.0                    0.0   
B00JAKXFQW                    0.0                    0.0   
B00JBK74IQ                    0.0                    0.0   
B00JBVWDB8                    0.0                    0.0   
B00JCA4GQS                    0.0                    0.0   
B00JIX4OTI                    0.0                    0.0   
B00JIX53PW                    0.0                    0.0   
B00JIXXHEG                    0.0                    0.0   
B00JJRMPPS                    0.0                    0.0   
B00JJS7JXK                    0.0                    0.0   
B00JKQV90A                    0.0                    0.0   
B00JKRE0JG                    0.0                    0.0   
B00JKRKFQI                    0.0                    0.0   
B00JKRKP22                    0.0                    0.0   
B00JXLGELG                    0.0                    0.0   
B00JXLGESY                    0.0                    0.0   
B00JXLGETI                    0.0                    0.0   
B00JXLGETS                    0.0                    0.0   
B00JXLGEUC                    0.0                    0.0   
B00JXLGF06                    0.0                    0.0   
B00K5UZP2S                    0.0                    0.0   
B00KLLBEPI                    0.0                    0.0   
B00KOO594O                    0.0                    0.0   
B00KOO599O                    0.0                    0.0   
B00KYA0RC2                    0.0                    0.0   

reviewerID  A0678500JUN3N7KUG4PS  A100UD67AHFODS  A100WO06OQR8BQ  \
asin                                                               
B00000JBLH                   0.0             0.0             0.0   
B00000JBLU     

In [16]:
from scipy.spatial.distance import correlation
neighbor = NearestNeighbors(n_neighbors=4, algorithm='auto', metric = 'correlation').fit(train_data_matrix)
distances, indices = neighbor.kneighbors(train_data_matrix)
print(distances)
print("__________________________")
print(indices)

[[0.00000000e+00 6.68894444e-01 6.72673165e-01 7.16357961e-01]
 [1.11022302e-16 9.01307246e-01 9.18604307e-01 9.52695273e-01]
 [0.00000000e+00 7.39125403e-01 9.48417962e-01 9.50309601e-01]
 ...
 [0.00000000e+00 7.13554050e-01 8.48792127e-01 8.90891055e-01]
 [0.00000000e+00 7.46679801e-01 7.49127397e-01 8.67017132e-01]
 [0.00000000e+00 5.00000000e-01 6.27322004e-01 6.59793091e-01]]
__________________________
[[   0  557 1259 1509]
 [   1  764 1582  229]
 [   2 1416  133 1703]
 ...
 [2417 1511 1388 1627]
 [2418 1271  992 1898]
 [2419 2159 2398 2016]]


In [17]:
# from sklearn.metrics.pairwise import pairwise_distances
# item_similarity = pairwise_distances(train_data_matrix, metric='cosine')
# item_similarity

In [18]:
reference_index = train_data_matrix.index.values
reference_index

array(['B00000JBLH', 'B00000JBLU', 'B00000JBNX', ..., 'B00KOO594O',
       'B00KOO599O', 'B00KYA0RC2'], dtype=object)

In [19]:
# train_data_matrix_Tr = train_data_matrix.T
# train_data_matrix_Tr.shape
# # item_similarity.shape

In [20]:
# item_prediction = train_data_matrix_Tr.dot(item_similarity)/(np.abs(item_similarity).sum(axis=1))
# item_prediction
# # item_prediction = item_prediction
# print(trainSet[1:2])
# print(trainSet[1:4]['reviewerID'].iat[0])
# print(trainSet[1:4]['asin'].iat[0])

for line in trainSet.values[:5]:
    print(line)

['B002FGUDBS' 'ATFBVUXDIRXT6' 5]
['B005IMAKYG' 'A3H7NPNDMGLOU4' 5]
['B0010JEJPC' 'AMW1OYXWOGZGJ' 5]
['B0085IQ28I' 'A15T9G38F589KM' 2]
['B009ZMWHIC' 'A32E5G5T902WRV' 1]


In [24]:
pred_rating = {}

for line in testSet.values[:500]:
    myuser = line[1]
    myitem = line[0]
    myrate = line[2]
# myuser = 'AMCAID3LTHKEC'   #testSet[1:4]['reviewerID'].iat[0]
# myitem = 'B00007LVCN'  #testSet[5:6]['asin'].iat[0]

    its_location, =np.where(reference_index == myitem)
    its_location = its_location[0]

    myitem_distances = distances[its_location:its_location+1][0]
    myitem_indices = indices[its_location:its_location+1][0]
    
    
    bi = mean_items.loc[myitem]['overall'] - mean_overall
    bx = mean_users.loc[myuser]['overall'] - mean_overall
    bxi = mean_overall + bi + bx

#     print(its_location)
#     print(myitem_distances)
#     print(myitem_indices)

#     print("____________________________________")

    item_occurences_in_train = []
    for i in range(4):
        item_occurence = trainSet.loc[(trainSet['asin'] == reference_index[myitem_indices[i]]) & (trainSet['reviewerID'] == myuser)]
        bi_n = mean_items.loc[reference_index[myitem_indices[i]]]['overall'] - mean_overall
        bix_n = mean_overall + bi_n + bx
        item_occurences_in_train.append((item_occurence, myitem_distances[i], bix_n))

#     print(item_occurences_in_train)

#     print("____________________________________")

    
#     print(bxi)

#     print("____________________________________")

    sim_rating = 0
#     divide_rating = 0
    # pred_rating((myuser,myitem)) = bxi + sim_rating

    for line in item_occurences_in_train:
#         print(line[0]['overall'].values)
        if not line[0].empty:
#             print(line[2])
            sim_rating = sim_rating + (line[0]['overall'].values-line[2])*(line[1])
            sim_rating=sim_rating[0]
#             print(sim_rating)
    #         divide_rating += (1-line[1]) 
#     print(sim_rating)

#     print("____________________________________")

    pred = bxi + sim_rating
    pred_rating[(myitem, myuser, myrate)] = pred

y_true = []
y_pred = []
for key in pred_rating:
    y_true.append(key[2])
    y_pred.append(pred_rating[key])
#     print(key," __ ", pred_rating[key])
# y_pred.append(pred_rating.values())
# print(y_pred[0])

mse = mean_squared_error(y_true, y_pred, multioutput='uniform_average')
print(mse)

ValueError: Input contains NaN, infinity or a value too large for dtype('float64').

In [55]:

# print(item_occurences_in_train[0][0].overall)
# trainSet['reviewerID']

In [56]:
# bi = mean_items.loc[myitem]['overall'] - mean_overall
# bi

In [57]:
# bx = mean_users.loc[myuser]['overall'] - mean_overall
# bx

In [58]:
# bxi = mean_overall + bi + bx
# bxi

In [59]:
# pred_rating = {}
# sim_rating = 0
# divide_rating = 0
# # pred_rating((myuser,myitem)) = bxi + sim_rating

# for line in item_occurences_in_train:
#     if not line[0].empty:
# #         print(line[0]['overall'])
#         sim_rating += (line[0]['overall'])*(line[1])
# #         divide_rating += (1-line[1]) 
# sim_rating = sim_rating
# sim_rating

In [60]:
# pred = bxi + sim_rating
# pred_rating[(myuser,myitem)] = pred
# pred_rating

In [7]:
# users_get_item = input()

# for line in testSet.values:
#     this_item = line[0]
#     its_user = line[1]
#     its_rating = line[2]

In [8]:
df_clean_matrix = df_clean.pivot(index='asin', columns='reviewerID', values='overall').fillna(0)
df_clean_matrix = df_clean_matrix.T
R = (df_clean_matrix).as_matrix()
R

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [9]:
user_ratings_mean = np.mean(R, axis = 1)
R_demeaned = R - user_ratings_mean.reshape(-1, 1)
R_demeaned

array([[-0.00785124, -0.00785124, -0.00785124, ..., -0.00785124,
        -0.00785124, -0.00785124],
       [-0.01033058, -0.01033058, -0.01033058, ..., -0.01033058,
        -0.01033058, -0.01033058],
       [-0.01446281, -0.01446281, -0.01446281, ..., -0.01446281,
        -0.01446281, -0.01446281],
       ...,
       [-0.01983471, -0.01983471, -0.01983471, ..., -0.01983471,
        -0.01983471, -0.01983471],
       [-0.02272727, -0.02272727, -0.02272727, ..., -0.02272727,
        -0.02272727, -0.02272727],
       [-0.00991736, -0.00991736, -0.00991736, ..., -0.00991736,
        -0.00991736, -0.00991736]])

In [10]:
from scipy.sparse.linalg import svds
U, sigma, Vt = svds(R_demeaned)

In [13]:
sigma = np.diag(sigma)

In [14]:
all_user_predicted_ratings = np.dot(np.dot(U, sigma), Vt) + user_ratings_mean.reshape(-1, 1)
preds_df = pd.DataFrame(all_user_predicted_ratings, columns = df_clean_matrix.columns)
preds_df['reviewerID'] = users_df
preds_df.set_index('reviewerID', inplace=True)
preds_df

asin                   B00000JBLH  B00000JBLU  B00000JBNX  B00000JBO8  \
reviewerID                                                              
A00473363TJ8YSZ3YAGG9    0.009418    0.009833    0.008133    0.009800   
A04324702R5O7JRSQNVAH    0.001954    0.009015    0.012244    0.007353   
A0678500JUN3N7KUG4PS     0.015533    0.016497    0.016022    0.016520   
A100UD67AHFODS           0.001849    0.008544    0.013974    0.007984   
A100WO06OQR8BQ           0.039053    0.041581    0.054373    0.023586   
A100ZQDV7L8PVV           0.006844    0.003561    0.003778    0.004035   
A101PIL0I3UZJJ           0.009101    0.009268    0.008157    0.009546   
A1027EV8A9PV1O           0.021102    0.021661    0.020561    0.022217   
A1047EDJ84IMAS           0.012319    0.012352    0.010700    0.012729   
A105S56ODHGJEK           0.016248    0.003216    0.034514    0.006478   
A106MB2IVYFRWR           0.008684    0.008688    0.007666    0.009005   
A106Q1A6LGU4DP           0.004313    0.003945    0.020318    0.003522   
A107H3XGCV6Y4Q           0.006641    0.004861    0.011885    0.004468   
A108B8OUQ0GHNF           0.012047    0.012243    0.010798    0.012628   
A10AQSHGUSJM5Q           0.011580    0.011490    0.010511    0.012032   
A10ASLX7DTTB6Z           0.003248   -0.003638    0.017119   -0.003371   
A10C4O0Q0TWXOL           0.007558    0.006965    0.007925    0.006273   
A10C5CJK1YKGV0           0.009115    0.002340    0.011051    0.005075   
A10E3F50DIUJEE           0.007000    0.005535    0.010770    0.006218   
A10ERSEFIAHESG           0.016988    0.016994    0.015852    0.017630   
A10G4BPT5MGBHY           0.030123    0.010813    0.002997    0.006590   
A10H24TDLK2VDP           0.009114    0.005711    0.014489    0.005699   
A10IFEQER9UA7T           0.014611    0.014971    0.013437    0.015214   
A10J0IVZ97LYJ9           0.010266    0.011363    0.010348    0.011301   
A10JPZAYDGFHEV           0.010439    0.008204    0.012071    0.009894   
A10KBYZJ0P3MPQ           0.005628    0.004661    0.010272    0.006203   
A10M2MLE2R0L6K           0.006998    0.008593    0.008709    0.006343   
A10O7THJ2O20AG           0.023436    0.019273    0.022034    0.022056   
A10PEXB6XAQ5XF           0.013222    0.010134    0.015383    0.009542   
A10Q2ZCYPEVHCU           0.006336    0.004340    0.014546    0.006622   
...                           ...         ...         ...         ...   
AZ74PFI67BCG2            0.009035    0.010848    0.008637    0.009849   
AZ8XSDMIX04VJ            0.034719    0.032665    0.033690    0.034995   
AZ9WQM7SLUX7E           -0.021492    0.001876    0.040230   -0.009254   
AZA55FJD7CCZN            0.007478    0.006894    0.012710    0.006704   
AZA595ZPIG240            0.010073    0.005478    0.009723    0.007349   
AZAC8O310IK4E            0.026414    0.026000    0.026896    0.026666   
AZAKCIFE27RAA           -0.026841    0.013271    0.033139   -0.003381   
AZBXKUH4AIW3X            0.022384    0.023498    0.021650    0.023906   
AZD7C4ZW00YKH            0.009899    0.009604    0.009092    0.010114   
AZD8SMNGQI98O            0.024564    0.032562    0.031357    0.021734   
AZE2ZP618W1EP           -0.001740    0.006497    0.002427   -0.000660   
AZF7A44AW3K0I            0.009440    0.009683    0.008365    0.009848   
AZFHSPEZUPGD2           -0.006709   -0.013159    0.015107   -0.011180   
AZGGG49I1J5E5            0.013860    0.013208    0.013749    0.014551   
AZH419IZOWETK            0.008136    0.006269    0.008103    0.006830   
AZIJ44I4NIO5M            0.017732    0.017549    0.015534    0.018116   
AZJFLPEG7D09G            0.007897    0.007024    0.007721    0.007601   
AZKGCE3LNX7WB            0.017137    0.016892    0.036488    0.011454   
AZL1JK2B50D2H            0.006317    0.004867    0.008559    0.006177   
AZMISC9FAUBIR           -0.004155    0.025001    0.004109    0.000727   
AZMY6E8B52L2T            0.027201    0.035106    0.041159    0.034457   
AZNUHQSHZHSUE            0.010267    0.011182    0.020823 

In [49]:
def recommend_method(predictions_df, movies_df, original_ratings_df, num_recommendations=5):
    
    # Get and sort the user's predictions
    sorted_user_predictions = predictions_df.loc['AZ9WQM7SLUX7E'].sort_values(ascending=False)
    
    # Get the user's data and merge in the movie information.
    user_data = original_ratings_df[original_ratings_df.reviewerID == 'AZ9WQM7SLUX7E']
    user_full = (user_data.merge(movies_df, how = 'left', left_on = 'asin', right_on = 'asin').
                     sort_values(['overall'], ascending=False)
                 )

    print ('User {0} has already rated {1} items.'.format('AZ9WQM7SLUX7E', user_full.shape[0]))
    print ('Recommending the highest {0} predicted ratings for items not already rated.'.format(num_recommendations))
    
    # Recommend the highest predicted rating movies that the user hasn't seen yet.
    recommendations = (movies_df[~movies_df['asin'].isin(user_full['asin'])].
         merge(pd.DataFrame(sorted_user_predictions).reset_index(), how = 'left',
               left_on = 'asin',
               right_on = 'asin').
         rename(columns = {'AZ9WQM7SLUX7E': 'Predictions'}).
         sort_values('Predictions', ascending = False).
                       iloc[:num_recommendations, :-1]
                      )

    return sorted_user_predictions

In [51]:
already_rated = recommend_method(preds_df, items_df, df_clean, 10)

User AZ9WQM7SLUX7E has already rated 21 items.
Recommending the highest 10 predicted ratings for items not already rated.


In [55]:
already_rated

asin
B0010T3QT2    3.077894
B0039N7ELS    2.457829
B0035FX5MC    1.505538
B0009F3P3U    1.412224
B0039N3QFQ    1.346022
B0000538AC    1.292004
B003FHBPRM    1.183063
B002K9IHJK    1.167714
B0039N3QO2    1.120583
B003FHF98S    1.109153
B000WU4H5C    1.068803
B002K9M7MS    0.971898
B0027CTFBO    0.946557
B002ECFIDG    0.928427
B000XSPEPA    0.818832
B000MFHX3U    0.745484
B004O49F7M    0.721668
B003H04A42    0.710097
B0039N7EI6    0.698696
B001BM2M8Y    0.650492
B002ECFILI    0.640541
B000I0VMMC    0.636779
B004VJSFG2    0.606254
B000ZHB2HS    0.601527
B003BHLMMY    0.591913
B0026ICM1E    0.581051
B000FH1J6C    0.555350
B002K9PIKG    0.550495
B002XYO84U    0.545924
B0006SV7Q2    0.530230
                ...   
B002ONCDH4   -0.025957
B00000JZKB   -0.026226
B001UQ6E58   -0.026958
B000HHS8C8   -0.028745
B001PMJXYG   -0.029076
B005OKRKRW   -0.030678
B002FGUDDG   -0.031169
B005ZOCWYI   -0.031726
B0019W4EIW   -0.034319
B004HY9IJE   -0.035263
B005GQKNL4   -0.037258
B004H3XKR6   -0.038644
B00FZ9

In [42]:
predictions

asin
1440  B0039N7ELS
450   B0009F3P3U
1467  B003FHBPRM
1283  B002K9IHJK
1438  B0039N3QO2
1468  B003FHF98S
788   B000WU4H5C
1286  B002K9M7MS
1207  B0027CTFBO
799   B000XSPEPA